### PR TITLE
Fix: V0.41 Resolve duplication issues with Scop2 tree node list, and ...

### PR DESCRIPTION
**Pull request by piehld**
... fix parent ID lists for nodes with multiple parents

### CODE REVIEW

**Comment by piehld** [comment]
@brindakv @chrstyan Can either of you please review these changes? I've confirmed on my own that they address the issues described in [RO-3020](https://rcsbpdb.atlassian.net/browse/RO-3020), as well as another issue that I discovered in the process as I describe in my [comment here](https://rcsbpdb.atlassian.net/browse/RO-3020?focusedCommentId=193980)).

Testing this in the full ExDB ETL pipeline was a bit difficult due to the code constantly trying to refetch the old `scop2.tar.gz` cache file from build locker as opposed to regenerating it from scratch, but I finally managed to force the pipeline to use the local copy and verified the `tree_scop2_node_list` collection in my dev ExDB now reflects the desired changes. I've now updated the cache file on both west and east build lockers (I backed up the previous version locally, too), so you should be able to run the pipeline using this `dev-ro-3020` branch and it should automatically retrieve the updated scop2.tar.gz file from build locker.

**Comment by piehld** [comment]
@josemduarte @valasatava FYI

**Comment by chrstyan** [comment]
@piehld ,
I am not familiar  about the logic how to fill in the data into the tree node. But the code looks OK to me. 

Li

**Comment by piehld** [comment]
Thanks @chrstyan! Yes the logic was quite complex for me to go through. Basically the parts I had to fix seemed like they were unintended consequences of a recent change John had made on 10-Sep-2021, in which he split the tree to have both Protein Type and Structural Class as roots, leading to a duplication of the lower level branches since both trees shared essentially all of the same branches.

Thanks for checking. I'll merge it now.

**Comment by piehld** [comment]
Oops meant to merge it first, then close it. Now reopening it.

**Pull request merged**
